version: "3.8"

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - type: volume
        source: mongodb
        target: /data/db
    environment:
      MONGO_DATA_DIR: /data/db
    # disable for first run
    command: [--auth]
      
volumes:
  mongodb:
    name: mongodb
