name: Continuous Integration
on: 
  push: 
    branches: 
      - main
  pull_request: 
  workflow_dispatch:


jobs:
  lint:
    name: Linting
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.9"]
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3

    - name: Install conda & dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: gsod-analysis
        auto-update-conda: true
        auto-activate-base: false
        python-version: ${{ matrix.python-version }}
        environment-file: environment.yml

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --fail-under=8 --disable=C0111 --rcfile=.pylintrc
