name: Continuous Integration
on: 
  push: 
    branches: 
      - main
  pull_request: 
  workflow_dispatch:


jobs:
  lint:
    name: Linting
    strategy:
      matrix:
        python-version: ["3.9"]
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3

    - name: Install conda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        source "$HOME/miniconda/etc/profile.d/conda.sh"
        hash -r
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda init bash

    - name: Install dependencies
      run: |
        conda env create -q -n test-environment --file environment.yml
        conda activate test-environment
        pip install --editable .
        pip install -r requirements.txt

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --fail-under=8 --disable=C0111 --rcfile=.pylintrc
